name: CI Pipeline Polimercado

on:
  push:
    branches: 
        - master
        - develop
        - feature/testing ]
  pull_request:
    branches:
        - master
        - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker images
      run: docker-compose build
      
    - name: Start containers
      run: docker-compose up -d
      
    - name: Wait for services to start
      run: sleep 15
      
    - name: Test database connection
      run: docker-compose exec -T web php test_db.php || echo "Connection test completed"
      
    - name: List running containers
      run: docker ps
      
    - name: Show web service logs
      run: docker-compose logs web
      
    - name: Show database service logs  
      run: docker-compose logs db
      
    - name: Stop containers
      run: docker-compose down